name: release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version number (x.y.z)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - name: npm version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ inputs.version }}
      - run: git show HEAD
      - name: npm login
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
      - run: npm publish
      - run: git push origin master v${{ inputs.version }}
